# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\hsexMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QDialog


# class Ui_sock5ProxySetting(object):
#     def setupUi(self, sock5ProxySetting):
#         sock5ProxySetting.setObjectName("sock5ProxySetting")
#         sock5ProxySetting.resize(290, 150)
#         self.groupBox = QtWidgets.QGroupBox(sock5ProxySetting)
#         self.groupBox.setGeometry(QtCore.QRect(10, 10, 271, 131))
#         self.groupBox.setObjectName("groupBox")
#         self.ip_port_lineEdit = QtWidgets.QLineEdit(self.groupBox)
#         self.ip_port_lineEdit.setGeometry(QtCore.QRect(100, 50, 161, 21))
#         self.ip_port_lineEdit.setObjectName("ip_port_lineEdit")
#         self.label = QtWidgets.QLabel(self.groupBox)
#         self.label.setGeometry(QtCore.QRect(10, 50, 91, 21))
#         self.label.setObjectName("label1")
#         self.label_2 = QtWidgets.QLabel(self.groupBox)
#         self.label_2.setGeometry(QtCore.QRect(50, 20, 191, 16))
#         self.label_2.setObjectName("label_2")
#         self.pushButton = QtWidgets.QPushButton(self.groupBox)
#         self.pushButton.setGeometry(QtCore.QRect(200, 90, 61, 31))
#         self.pushButton.setObjectName("origin_path_button")
#
#         self.retranslateUi(sock5ProxySetting)
#         QtCore.QMetaObject.connectSlotsByName(sock5ProxySetting)
#
#     def retranslateUi(self, sock5ProxySetting):
#         _translate = QtCore.QCoreApplication.translate
#         sock5ProxySetting.setWindowTitle(_translate("sock5ProxySetting", "socks5代理设置"))
#         self.groupBox.setTitle(_translate("sock5ProxySetting", "请输入参数"))
#         self.label.setText(_translate("sock5ProxySetting", "请输入IP和端口"))
#         self.label_2.setText(_translate("sock5ProxySetting", "示例：socks5h://127.0.0.1:7890"))
#         self.pushButton.setText(_translate("sock5ProxySetting", "确 定"))


class proxySocksSetting(QDialog):
    signal = QtCore.pyqtSignal(str)

    def __init__(self):
        super(proxySocksSetting, self).__init__()
        self.init_ui()
        # self.show()

    def init_ui(self):
        self.setObjectName("sock5ProxySetting")
        self.resize(290, 150)
        self.groupBox = QtWidgets.QGroupBox(self)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 271, 131))
        self.groupBox.setObjectName("groupBox")
        self.ip_port_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.ip_port_lineEdit.setGeometry(QtCore.QRect(100, 50, 161, 21))
        self.ip_port_lineEdit.setObjectName("ip_port_lineEdit")
        self.label1 = QtWidgets.QLabel(self.groupBox)
        self.label1.setGeometry(QtCore.QRect(10, 50, 91, 21))
        self.label1.setObjectName("label1")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(50, 20, 191, 16))
        self.label_2.setObjectName("label_2")
        self.sumbit_button = QtWidgets.QPushButton(self.groupBox)
        self.sumbit_button.setGeometry(QtCore.QRect(200, 90, 61, 31))
        self.sumbit_button.setObjectName("origin_path_button")

        self.setWindowTitle("代理设置")
        self.groupBox.setTitle("请输入参数")
        self.label1.setText("请输入IP和端口")
        self.label_2.setText("示例：127.0.0.1:7890")
        self.sumbit_button.setText("确 定")





if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    main_window = proxySocksSetting()
    main_window.show()
    sys.exit(app.exec())

